"""add comments

Revision ID: 0a57c52766ea
Revises: 82779280f217
Create Date: 2022-01-03 13:29:13.680645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a57c52766ea'
down_revision = '82779280f217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('text', sa.String(length=600), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('reply_to_message_id', sa.Integer(), nullable=True),
    sa.Column('user_id_from', sa.Integer(), nullable=False),
    sa.Column('game_id_from', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id_from'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id_from'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
