"""migration

Revision ID: 82779280f217
Revises: a238987e339c
Create Date: 2021-12-14 21:34:11.936461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82779280f217'
down_revision = 'a238987e339c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('subgenre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('genre_subgenre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('subgenre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['subgenre_id'], ['subgenre.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('genre_id', 'subgenre_id')
    )
    op.create_table('game_genre_subgenre',
    sa.Column('genre_subgenre_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['genre_subgenre_id'], ['genre_subgenre.id'], ),
    sa.PrimaryKeyConstraint('genre_subgenre_id', 'game_id')
    )
    op.create_table('user_game',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'game_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_game')
    op.drop_table('game_genre_subgenre')
    op.drop_table('genre_subgenre')
    op.drop_table('subgenre')
    op.drop_table('genre')
    op.drop_table('game')
    # ### end Alembic commands ###
